stages:
  - build
  - deploy
  - notify

variables:
  DOCKER_IMAGE_TAG: $CI_REGISTRY_IMAGE/db_migrate:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA
  DOCKER_IMAGE_LATEST: $CI_REGISTRY_IMAGE/db_migrate:$CI_COMMIT_REF_SLUG-latest
  INIT_IMAGE_TAG: $CI_REGISTRY_IMAGE/db_init:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA
  INIT_IMAGE_LATEST: $CI_REGISTRY_IMAGE/db_init:$CI_COMMIT_REF_SLUG-latest

build_db:
  stage: build
  image: docker:27.5.0
  services:
    - docker:27.5.0-dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - echo "Building Migration Service for branch $CI_COMMIT_REF_SLUG..."

    - docker pull $DOCKER_IMAGE_LATEST || true
    - docker build -f Dockerfile.migrate --cache-from $DOCKER_IMAGE_LATEST -t $DOCKER_IMAGE_TAG -t $DOCKER_IMAGE_LATEST .

    - docker pull $INIT_IMAGE_LATEST || true
    - docker build -f Dockerfile.init --cache-from $INIT_IMAGE_LATEST -t $INIT_IMAGE_TAG -t $INIT_IMAGE_LATEST .

    - docker push $DOCKER_IMAGE_TAG
    - docker push $DOCKER_IMAGE_LATEST
    - docker push $INIT_IMAGE_TAG
    - docker push $INIT_IMAGE_LATEST
  rules:
    - if: $CI_COMMIT_BRANCH == "stage"
    - if: $CI_COMMIT_BRANCH == "main"

notify_db_change:
  stage: notify
  image: curlimages/curl:latest
  script:
    - |
      curl -X POST "https://api.telegram.org/bot${TELEGRAM_TOKEN}/sendMessage" \
      -d "chat_id=${TELEGRAM_CHAT_ID}" \
      -d "message_thread_id=249" \
      -d "parse_mode=HTML" \
      -d "text=‼️ <b>DB Alert</b>%0A👤 Автор: ${GITLAB_USER_NAME}%0A📂 Файлы: <code>${CHANGED_FILES}</code>%0A🔗 <a href='${CI_PROJECT_URL}/-/commit/${CI_COMMIT_SHA}'>Commit Link</a>"
  rules:
    - changes:
        - "src/db/**/*"
        - "alembic/**/*"
        - "seed/**/*"
        - "alembic.ini"
      when: always

.deploy_template:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh-client bash
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | base64 -d | ssh-add -
    - mkdir -p ~/.ssh && chmod 700 ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\tPort $TARGET_PORT\n\n" > ~/.ssh/config
  script:
    - echo "Deploying to $TARGET_HOST..."
    - ssh $TARGET_USER@$TARGET_HOST "mkdir -p $DEPLOY_PATH"
    - scp docker-compose.yml $TARGET_USER@$TARGET_HOST:$DEPLOY_PATH/docker-compose.yml
    - cat "$TARGET_ENV_FILE" | ssh $TARGET_USER@$TARGET_HOST "cat > $DEPLOY_PATH/.env"

    - ssh $TARGET_USER@$TARGET_HOST "echo '' >> $DEPLOY_PATH/.env && echo 'migrate=$DOCKER_IMAGE_TAG' >> $DEPLOY_PATH/.env && echo 'init=$INIT_IMAGE_TAG' >> $DEPLOY_PATH/.env && echo 'COMPOSE_PROFILES=$TARGET_PROFILES' >> $DEPLOY_PATH/.env"

    - |
      ssh $TARGET_USER@$TARGET_HOST "
        cd $DEPLOY_PATH
        
        docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
        
        docker compose pull
        
        docker compose up -d --remove-orphans
        
        docker image prune -a -f --filter \"until=24h\"
      "

deploy_stage:
  extends: .deploy_template
  variables:
    TARGET_PORT: $SSH_PORT_STAGE
    TARGET_HOST: $SSH_HOST_STAGE
    TARGET_USER: $SSH_USER_STAGE
    TARGET_ENV_FILE: $STAGING_ENV_FILE
    DEPLOY_PATH: "$BASE_DEPLOY_PATH/db"
    TARGET_PROFILES: "seed"
  environment:
    name: staging
  rules:
    - if: $CI_COMMIT_BRANCH == "stage"

deploy_prod:
  extends: .deploy_template
  variables:
    TARGET_PORT: $SSH_PORT_PROD
    TARGET_HOST: $SSH_HOST_PROD
    TARGET_USER: $SSH_USER_PROD
    TARGET_ENV_FILE: $PROD_ENV_FILE
    DEPLOY_PATH: "$BASE_DEPLOY_PATH/db"
    TARGET_PROFILES: ""
  environment:
    name: production
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  when: manual
